### ISSUE TITLE
Notice: get_cart was called incorrectly. 

### ISSUE THREAD

**Issue by HammenWS** [JeroenSormani/WooCommerce-Advanced-Free-Shipping#23]
The match_condition filters use use the WooCommerce use the WC_Cart object to get the contents of the cart.

But WooCommerce now gives a notice when you use that method before de the 'wp_loaded' action is triggered. I think to prevent race conditions.

A solution is to extract the add_filters int the WAFS_Match_Conditions contstructor to it's own method and call it within a 'wp_loaded' action.

```
class WAFS_Match_Conditions {


	/**
	 * Constructor.
	 *
	 * @since 1.0.0
	 */
	public function __construct() {

		add_action('wp_loaded', array($this, 'add_filters'));
		
	}

	public function add_filters() {
		add_filter( 'wafs_match_condition_subtotal', array( $this, 'wafs_match_condition_subtotal' ), 10, 3 );
		add_filter( 'wafs_match_condition_subtotal_ex_tax', array( $this, 'wafs_match_condition_subtotal_ex_tax' ), 10, 3 );
		add_filter( 'wafs_match_condition_tax', array( $this, 'wafs_match_condition_tax' ), 10, 3 );
		add_filter( 'wafs_match_condition_quantity', array( $this, 'wafs_match_condition_quantity' ), 10, 3 );
		add_filter( 'wafs_match_condition_contains_product', array( $this, 'wafs_match_condition_contains_product' ), 10, 3 );
		add_filter( 'wafs_match_condition_coupon', array( $this, 'wafs_match_condition_coupon' ), 10, 3 );
		add_filter( 'wafs_match_condition_weight', array( $this, 'wafs_match_condition_weight' ), 10, 3 );
		add_filter( 'wafs_match_condition_contains_shipping_class', array( $this, 'wafs_match_condition_contains_shipping_class' ), 10, 3 );

		add_filter( 'wafs_match_condition_zipcode', array( $this, 'wafs_match_condition_zipcode' ), 10, 3 );
		add_filter( 'wafs_match_condition_city', array( $this, 'wafs_match_condition_city' ), 10, 3 );
		add_filter( 'wafs_match_condition_state', array( $this, 'wafs_match_condition_state' ), 10, 3 );
		add_filter( 'wafs_match_condition_country', array( $this, 'wafs_match_condition_country' ), 10, 3 );
		add_filter( 'wafs_match_condition_role', array( $this, 'wafs_match_condition_role' ), 10, 3 );

		add_filter( 'wafs_match_condition_width', array( $this, 'wafs_match_condition_width' ), 10, 3 );
		add_filter( 'wafs_match_condition_height', array( $this, 'wafs_match_condition_height' ), 10, 3 );
		add_filter( 'wafs_match_condition_length', array( $this, 'wafs_match_condition_length' ), 10, 3 );
		add_filter( 'wafs_match_condition_stock', array( $this, 'wafs_match_condition_stock' ), 10, 3 );
		add_filter( 'wafs_match_condition_stock_status', array( $this, 'wafs_match_condition_stock_status' ), 10, 3 );
		add_filter( 'wafs_match_condition_category', array( $this, 'wafs_match_condition_category' ), 10, 3 );
	}
```

This solves the problem. 

Kind Regards,
Ramiro Hammen

**Comment by HammenWS** [comment]
I have a pull request ready but I don't have the permission to do a PR ;)

**Comment by JeroenSormani** [comment]
Hi @HammenWS ,

Can you elaborate where it is calling the matching functions before `wp_loaded`? The filters are added soon (not sure if its before wp_loaded), but shouldn't be called until the cart calculates the shipping cost. 

In what version of WC is this,, Are you on a dev branch? 
I haven't seen any errors within WC yet.

Let me know!
Thanks

**Comment by HammenWS** [comment]
Check this function in the WC_Cart class of WooCommerce 2.6

```
		/**
		 * Returns the contents of the cart in an array.
		 *
		 * @return array contents of the cart
		 */
		public function get_cart() {
			if ( ! did_action( 'wp_loaded' ) ) {
				_doing_it_wrong( __FUNCTION__, __( 'Get cart should not be called before the wp_loaded action.', 'woocommerce' ), '2.3' );
			}
			if ( ! did_action( 'woocommerce_cart_loaded_from_session' ) ) {
				$this->get_cart_from_session();
			}
			return array_filter( (array) $this->cart_contents );
		}
```
This was throwing the notice at the moment your matching filters were applied. I guess it's because my local php is blazing fast. At least my fix worked.

**Comment by JeroenSormani** [comment]
@HammenWS maybe there's something else on your install that is calling the shipping rates too early? 
I followed the code waay back and the filters that I'm adding / the matching functionality is only called when WC is retrieving the shipping rates. 

As far as I can find this is done after wp_loaded.

I can't replicate any notices // haven't heard anyone else about this with any of my plugins. Can you check if there's anything else on site doing that?

Thanks

**Comment by HammenWS** [comment]
@JeroenSormani I just found out it is the WPML Media plugin causing this behavior. I do not know why though..

**Comment by JeroenSormani** [comment]
@HammenWS this person also has the same issue: https://wordpress.org/support/topic/empty-card-with-error-on-anonymous-users/#post-8721144

Referring to WooCommerce Multilangual plugin, could that be possible too?

**Comment by JeroenSormani** [comment]
@HammenWS just posted to that topic I linked above, found the method that causes this error: https://cl.ly/0L1g1c3P080I

Could you maybe also pass this to your contact at WPML?
