### ISSUE TITLE
Cart total condition

### ISSUE THREAD

**Issue by fabricsilva** [JeroenSormani/WooCommerce-Advanced-Free-Shipping#26]
Hello.
I'm using this plugin to enable free shipping when a order reach a amount of $100 in products. So I'm using subtotal condition with operator 'greater than or equal' e 100 as value for comparison.
My trouble is when some order got a discount coupon. 
For example, if an order have a subtotal of $105 it is eligible for free shipping, but applying a 10% discount coupon (-$10,50) the order total result in $94,50 with free shipping.
I would like to use a condition with cart total >= $100 to enable free shipping.

I really appreciate any help you can provide.

**Comment by fabricsilva** [comment]
Is it acceptable to create a new condition extending WPC_Condition as wpc-subtotal-condition.php do and returning WC()->cart->total in get_compare_value() method?

Where more should I change to include this condition? 
Could you provide some instructions?

I'll open a PR to contribute if you agree with my collab.

Many thanks for considering my request.

**Comment by JeroenSormani** [comment]
@fabricsilva yes you can extend the `WPC_Condition` class, thats where its meant for ;-)

Do note that the total amount should also include the shipping cost, which as you can imagine can give conflicts like the chicken and the egg.

I don't have the solution / instructions available for this plugin, but I do have a solution available for this for the [Advanced Shipping](http://codecanyon.net/item/woocommerce-advanced-shipping/8634573) plugin where I have a custom condition for (that uses the legacy way, not the WPC_Condition yet).

Due to the confusion of the chicken/egg thing it won't be added to the core plugin ;-)

**Comment by fabricsilva** [comment]
Hey @JeroenSormani ,
Thank you so much for your reply.

**Comment by skydogtk** [comment]
I solved my situation introducing the "subtotal except discounts" condition. 
You may see my commit [here](https://github.com/skydogtk/WooCommerce-Advanced-Free-Shipping/commit/d879caee8eb714dccd4bd0ed6e62281b0b427e39).
Could you consider integrate this new condition to the plugin core?

Thanks again for your support.

**Comment by JeroenSormani** [comment]
Looks good :+1: 
I would recommend to put it in a separate code snippet so you can continue to use the base plugin without overwriting your own code. You can still use most of the code you wrote, and just hook it in through action/filter hooks :-)

At this moment I'm not planning on adding new conditions to the plugin (maybe to the library) that aren't frequently requested. Subtotal ex discounts is on the short list when new conditions are added, but the number of requests currently doesn't warrant adding it to the conditions list directly.

Reasoning behind that is to try to keep the options limited to not overwhelm users with options. I've got about a dozen other conditions that are requested as many times as subtotal ex discount, and as you can imagine adding a dozen more conditions would make probably >50% of the users less comfortable with the plugin, while those conditions are only used by <5%
